apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-{{.Values.user.name}}-api
  labels:
    app: {{.Values.user.name}}
    env: dev
    project: axul
spec:
  replicas: {{.Values.user.replicas}}
  selector:
    matchLabels:
      app: {{.Values.user.name}}
  template:
    metadata:
      labels:
        app: {{.Values.user.name}}
    spec:
      containers:
      - name: {{.Values.user.name}}
        image: {{.Values.user.image.url}}:{{.Values.user.image.version}}
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-{{.Values.user.name}}-api
  labels:
    app: {{.Values.user.name}}
    env: dev
    project: axul
spec:
  type: NodePort
  selector:
    app: {{.Values.user.name}}
  ports:
    - name: http
      protocol: TCP
      port: {{.Values.user.port.http}}
      targetPort: {{.Values.user.port.http}}
    - name: grpc
      protocol: TCP
      port: {{.Values.user.port.grpc}}
      targetPort: {{.Values.user.port.grpc}}
